const Book=require("../models/Book");
const asyncHandler=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const createBook=asyncHandler(async(req,res)=>{const book=await Book.create(req.body);res.status(201).json({success:true,data:book});});
const getBooks=asyncHandler(async(req,res)=>{const page=Math.max(Number(req.query.page)||1,1);const limit=Math.min(Math.max(Number(req.query.limit)||20,1),100);const filter={};if(req.query.search){const p=new RegExp(String(req.query.search).replace(/[.*+?^$()|[\]\\]/g,"\\$&"),"i");filter.$or=[{title:p},{author:p},{isbn:p}];}if(req.query.available!==undefined)filter.available=req.query.available==="true";const [data,total]=await Promise.all([Book.find(filter).sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),Book.countDocuments(filter)]);res.json({success:true,data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}});});
const getBookById=asyncHandler(async(req,res)=>{const book=await Book.findById(req.params.id).lean();if(!book)return res.status(404).json({success:false,message:"Book not found"});res.json({success:true,data:book});});
const updateBook=asyncHandler(async(req,res)=>{const book=await Book.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!book)return res.status(404).json({success:false,message:"Book not found"});res.json({success:true,data:book});});
const deleteBook=asyncHandler(async(req,res)=>{const book=await Book.findByIdAndDelete(req.params.id);if(!book)return res.status(404).json({success:false,message:"Book not found"});res.json({success:true,message:"Book deleted successfully"});});
const updateAvailability=asyncHandler(async(req,res)=>{if(typeof req.body.available!=="boolean")return res.status(400).json({success:false,message:"available must be a boolean"});const book=await Book.findByIdAndUpdate(req.params.id,{available:req.body.available},{new:true,runValidators:true});if(!book)return res.status(404).json({success:false,message:"Book not found"});res.json({success:true,data:book});});
module.exports={createBook,getBooks,getBookById,updateBook,deleteBook,updateAvailability};
